// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ounloohylrjbfrdmrkde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91bmxvb2h5bHJqYmZyZG1ya2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzQ5NDQsImV4cCI6MjA1NzQxMDk0NH0.ltp_EfkIm5xyB62kbYNBAz8TWltVJR50M84fooU8mgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);